import { StyleSheet } from 'react-native';

const palette = {
  appBg: '#f3f6fa',
  surface: '#ffffff',
  surfaceSoft: '#f8fafc',
  surfaceWarm: '#fffaf0',
  ink: '#101828',
  text: '#1f2937',
  muted: '#667085',
  faint: '#98a2b3',
  line: '#d9e2ec',
  lineSoft: '#e8edf3',
  navy: '#0f2742',
  navy2: '#163a5f',
  blue: '#1d5f99',
  blueSoft: '#edf6ff',
  green: '#0f766e',
  greenDark: '#0f5f45',
  greenSoft: '#eaf8f2',
  gold: '#b88a16',
  goldSoft: '#fff7dd',
  red: '#b42318',
  redSoft: '#fff1f0',
};

const cardShadow = {
  shadowColor: '#101828',
  shadowOpacity: 0.08,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 4 },
  elevation: 3,
};

const liftedShadow = {
  shadowColor: '#101828',
  shadowOpacity: 0.14,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 8 },
  elevation: 6,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.navy },
  keyboard: { flex: 1 },
  content: { flex: 1, backgroundColor: palette.appBg },
  contentInner: { padding: 14, paddingBottom: 28 },
  stack: { gap: 14 },
  mutedText: { color: palette.muted, fontSize: 14, lineHeight: 20, fontWeight: '600' },

  loginSafeArea: { flex: 1, backgroundColor: palette.navy },
  loginScroll: { flexGrow: 1, justifyContent: 'center', gap: 18, padding: 18, backgroundColor: palette.navy },
  loginBrandBlock: {
    alignItems: 'center',
    gap: 7,
    paddingTop: 10,
  },
  loginCard: {
    gap: 16,
    padding: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d8e1eb',
    backgroundColor: palette.surface,
    ...liftedShadow,
  },
  loginLogoFrame: {
    width: 102,
    height: 102,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#38566f',
    backgroundColor: '#173452',
  },
  loginLogo: {
    width: 88,
    height: 88,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2a4967',
  },
  loginKicker: { color: '#d8b04c', fontSize: 12, fontWeight: '900', letterSpacing: 0, textAlign: 'center' },
  loginTitle: { color: '#ffffff', fontSize: 30, fontWeight: '900', letterSpacing: 0, textAlign: 'center' },
  loginSubtitle: { color: '#d5dfeb', fontSize: 14, lineHeight: 21, textAlign: 'center', fontWeight: '800' },
  loginFormHeader: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 2,
  },
  loginFormTitle: { color: palette.ink, fontSize: 18, fontWeight: '900' },
  loginFormHint: { color: palette.muted, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  loginForm: { gap: 12, paddingTop: 4 },
  loginError: {
    padding: 11,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f3b5ae',
    backgroundColor: palette.redSoft,
    color: palette.red,
    fontSize: 13,
    fontWeight: '800',
  },
  loginButton: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 8,
    backgroundColor: palette.navy,
    ...cardShadow,
  },
  loginSuccessButton: { backgroundColor: palette.green },
  loginButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '900' },
  loginRoleButtons: { flexDirection: 'row', gap: 10, paddingTop: 2 },
  loginRoleButton: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.blueSoft,
  },
  loginRoleButtonText: { color: palette.navy2, fontSize: 13, fontWeight: '900' },
  seedUsers: { gap: 9, paddingTop: 4 },
  seedTitle: { color: palette.text, fontSize: 12, fontWeight: '900' },
  seedUserRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  seedRole: { color: palette.navy2, fontSize: 13, fontWeight: '900' },
  seedCredential: { color: palette.muted, fontSize: 12, fontWeight: '700' },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    backgroundColor: palette.navy,
    borderBottomWidth: 1,
    borderBottomColor: '#1c3a59',
  },
  menuButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#38566f',
    backgroundColor: '#173452',
  },
  headerLogo: { width: 46, height: 46, borderRadius: 8, borderWidth: 1, borderColor: '#2a4967' },
  headerText: { flex: 1, minWidth: 0 },
  kicker: { color: '#a7b8cc', fontSize: 10, fontWeight: '900', letterSpacing: 0 },
  title: { color: '#ffffff', fontSize: 19, fontWeight: '900', letterSpacing: 0 },
  signedInLine: { marginTop: 2, color: '#d5dfeb', fontSize: 11, fontWeight: '800' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  syncStatusBadge: {
    maxWidth: 82,
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#38566f',
    backgroundColor: '#173452',
  },
  syncStatusBadgeOnline: { borderColor: '#1f6964', backgroundColor: '#102f35' },
  syncStatusBadgeOffline: { borderColor: '#713436', backgroundColor: '#311b24' },
  syncStatusText: { color: '#d5dfeb', fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  totalBadge: {
    minWidth: 94,
    paddingHorizontal: 9,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#102f35',
    borderWidth: 1,
    borderColor: '#1f6964',
  },
  totalBadgeLabel: { color: '#9bd7ca', fontSize: 10, fontWeight: '900' },
  totalBadgeValue: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  logoutButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#713436',
    backgroundColor: '#311b24',
  },

  sideMenuLayer: { ...StyleSheet.absoluteFillObject, zIndex: 40, flexDirection: 'row' },
  sideMenuBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(16, 24, 40, 0.48)' },
  sideMenuPanel: {
    width: 312,
    maxWidth: '86%',
    height: '100%',
    paddingTop: 14,
    paddingHorizontal: 14,
    paddingBottom: 18,
    backgroundColor: palette.surface,
    borderRightWidth: 1,
    borderRightColor: palette.line,
    shadowColor: '#101828',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 6, height: 0 },
    elevation: 12,
  },
  sideMenuHeader: {
    minHeight: 92,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 8,
    backgroundColor: palette.navy,
  },
  sideMenuLogo: { width: 52, height: 52, borderRadius: 8, borderWidth: 1, borderColor: '#2e4b68' },
  sideMenuKicker: { color: '#a7b8cc', fontSize: 10, fontWeight: '900', letterSpacing: 0 },
  sideMenuTitle: { color: '#ffffff', fontSize: 16, fontWeight: '900' },
  sideMenuRole: { color: '#d8b04c', fontSize: 11, fontWeight: '900' },
  sideMenuClose: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#38566f',
    backgroundColor: '#173452',
  },
  sideMenuScroll: { flex: 1, marginTop: 8 },
  sideMenuScrollContent: { paddingBottom: 8 },
  sideMenuItems: { gap: 8, paddingVertical: 8, paddingRight: 2 },
  sideMenuItem: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surface,
  },
  sideMenuItemActive: { borderColor: palette.navy, backgroundColor: palette.navy },
  sideMenuItemText: { color: palette.text, fontSize: 15, fontWeight: '900' },
  sideMenuItemTextActive: { color: '#ffffff' },
  sideMenuLogout: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f3b5ae',
    backgroundColor: palette.redSoft,
  },
  sideMenuLogoutText: { color: palette.red, fontSize: 14, fontWeight: '900' },

  stepBar: {
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: palette.surface,
    borderBottomWidth: 1,
    borderBottomColor: palette.lineSoft,
  },
  stepButton: {
    flex: 1,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surfaceSoft,
  },
  stepButtonActive: { backgroundColor: palette.navy, borderColor: palette.navy },
  stepButtonText: { color: palette.muted, fontSize: 10, fontWeight: '800' },
  stepButtonTextActive: { color: '#ffffff' },
  footerNav: {
    flexDirection: 'row',
    gap: 10,
    padding: 12,
    backgroundColor: palette.surface,
    borderTopWidth: 1,
    borderTopColor: palette.line,
  },
  navButton: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surface,
  },
  navButtonDisabled: { opacity: 0.45 },
  navButtonText: { color: palette.text, fontWeight: '900' },
  primaryNavButton: {
    flex: 1,
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 8,
    backgroundColor: palette.navy,
    ...cardShadow,
  },
  primaryNavText: { color: '#ffffff', fontWeight: '900' },

  card: {
    borderRadius: 8,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    ...cardShadow,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: 13,
    borderBottomWidth: 1,
    borderBottomColor: palette.lineSoft,
  },
  cardTitleWrap: { flexDirection: 'row', alignItems: 'center', gap: 9, flex: 1, minWidth: 0 },
  cardIconBadge: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: palette.navy,
  },
  cardTitle: { color: palette.ink, fontSize: 16, fontWeight: '900', letterSpacing: 0 },
  cardBody: { gap: 12, padding: 13 },

  field: { gap: 6 },
  inputLabel: { color: palette.text, fontSize: 12, fontWeight: '900' },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: palette.surfaceSoft,
    color: palette.ink,
    fontSize: 15,
    fontWeight: '600',
  },
  inputDisabled: { backgroundColor: '#edf1f5', color: palette.muted },
  textarea: { minHeight: 88, textAlignVertical: 'top' },
  datePickerButton: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: palette.surfaceSoft,
  },
  datePickerText: { flex: 1, color: palette.ink, fontSize: 15, fontWeight: '800' },
  datePickerWrap: {
    overflow: 'hidden',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surface,
  },
  managerDropdownList: {
    maxHeight: 280,
    overflow: 'hidden',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surface,
  },
  managerDropdownScroll: { maxHeight: 220 },
  managerDropdownItem: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: palette.lineSoft,
    backgroundColor: palette.surface,
  },
  managerDropdownItemActive: { backgroundColor: palette.navy },
  managerDropdownAddButton: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderTopWidth: 1,
    borderTopColor: palette.lineSoft,
    backgroundColor: palette.blueSoft,
  },
  managerModalLayer: {
    flex: 1,
    justifyContent: 'center',
    padding: 16,
    backgroundColor: 'rgba(16, 24, 40, 0.48)',
  },
  managerModalBackdrop: { ...StyleSheet.absoluteFillObject },
  managerModalCard: {
    maxHeight: '88%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surface,
    ...liftedShadow,
  },
  datePickerDoneButton: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: 1,
    borderTopColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  datePickerDoneText: { color: palette.navy2, fontSize: 14, fontWeight: '900' },
  segmented: { flexDirection: 'row', gap: 8 },
  segment: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surfaceSoft,
    paddingHorizontal: 8,
  },
  segmentActive: { backgroundColor: palette.navy, borderColor: palette.navy },
  segmentText: { color: palette.muted, fontSize: 13, fontWeight: '800', textAlign: 'center' },
  segmentTextActive: { color: '#ffffff' },
  smallButton: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.blueSoft,
  },
  smallButtonText: { color: palette.navy2, fontWeight: '900' },

  pageHero: {
    minHeight: 94,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1f3b57',
    backgroundColor: palette.navy,
    ...liftedShadow,
  },
  pageKicker: { color: '#a7b8cc', fontSize: 11, fontWeight: '900' },
  pageTitle: { color: '#ffffff', fontSize: 24, fontWeight: '900', letterSpacing: 0 },
  pageSubtitle: { color: '#d8b04c', fontSize: 12, lineHeight: 17, fontWeight: '900' },
  pagePrimaryButton: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: palette.greenDark,
  },
  pagePrimaryButtonText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },

  dashboardHero: {
    gap: 14,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1f3b57',
    backgroundColor: palette.navy,
    ...liftedShadow,
  },
  dashboardHeroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  dashboardHeroTopCompact: { flexDirection: 'column', alignItems: 'flex-start', gap: 10 },
  dashboardIdentity: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1, minWidth: 0 },
  dashboardAvatar: {
    width: 50,
    height: 50,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1d5f99',
    borderWidth: 1,
    borderColor: '#3b75a8',
  },
  dashboardKicker: { color: '#a7b8cc', fontSize: 11, fontWeight: '900' },
  dashboardTitle: { color: '#ffffff', fontSize: 24, fontWeight: '900', letterSpacing: 0 },
  dashboardSubtitle: { color: '#d8b04c', fontSize: 13, fontWeight: '900' },
  dashboardPill: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#173452',
    color: '#e7edf4',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
  },
  dashboardPillCompact: { alignSelf: 'flex-start', marginTop: -2 },
  dashboardMetricStrip: { flexDirection: 'row', gap: 10 },
  dashboardMetricStripCompact: { flexDirection: 'column', gap: 8 },
  dashboardMetric: {
    flex: 1,
    minHeight: 76,
    justifyContent: 'center',
    gap: 4,
    padding: 11,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#345978',
    backgroundColor: '#173452',
  },
  dashboardMetricLabel: { color: '#a7b8cc', fontSize: 11, fontWeight: '900' },
  dashboardMetricValue: { color: '#ffffff', fontSize: 20, fontWeight: '900' },
  dashboardMetricValueRed: { color: '#fda29b' },
  dashboardMetricHint: { color: '#d8b04c', fontSize: 12, fontWeight: '900' },
  dashboardStatHeader: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statCard: {
    flexBasis: '31%',
    flexGrow: 1,
    minWidth: 96,
    minHeight: 84,
    justifyContent: 'center',
    gap: 5,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  statCardCompact: { flexBasis: '100%', minWidth: 0 },
  statCardTwoColumn: { flexBasis: '48%', minWidth: 0 },
  dashboardMetricCompact: { flexBasis: '100%', width: '100%', minWidth: 0 },
  statLabel: { color: palette.muted, fontSize: 11, fontWeight: '900' },
  statValue: { color: palette.ink, fontSize: 18, fontWeight: '900' },
  statValueGreen: { color: palette.greenDark },
  statValueRed: { color: palette.red },
  reportGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  reportTile: {
    flexBasis: '31%',
    flexGrow: 1,
    minWidth: 98,
    minHeight: 88,
    justifyContent: 'center',
    gap: 4,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  reportLabel: { color: palette.muted, fontSize: 11, fontWeight: '900' },
  reportValue: { color: palette.ink, fontSize: 20, fontWeight: '900' },
  reportSubValue: { color: palette.blue, fontSize: 12, fontWeight: '900' },
  reportList: { gap: 9 },
  reportSectionTitle: { color: palette.text, fontSize: 13, fontWeight: '900' },
  reportRow: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: 11,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  reportRowTitle: { color: palette.ink, fontSize: 14, fontWeight: '900' },
  reportRowMeta: { color: palette.muted, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  reportRowAmount: {
    minWidth: 104,
    maxWidth: 144,
    color: palette.greenDark,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  reportRowAmountRed: { color: palette.red },
  clientRank: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.goldSoft,
    borderWidth: 1,
    borderColor: '#eed8a5',
  },
  clientRankText: { color: '#7a5309', fontSize: 12, fontWeight: '900' },
  quickActions: { gap: 10 },
  quickActionButton: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  quickActionText: { flex: 1, gap: 2, minWidth: 0 },
  quickActionTitle: { color: palette.ink, fontSize: 15, fontWeight: '900' },
  quickActionSubtitle: { color: palette.muted, fontSize: 12, fontWeight: '700' },

  deviceShareSignal: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#713436',
    backgroundColor: '#311b24',
  },
  deviceShareSignalOnline: {
    borderColor: '#1f6964',
    backgroundColor: '#102f35',
  },
  deviceShareStatusGrid: { flexDirection: 'row', gap: 10 },
  deviceShareStatusTile: {
    flex: 1,
    minHeight: 76,
    justifyContent: 'center',
    gap: 5,
    padding: 11,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  deviceShareStatusValue: { color: palette.ink, fontSize: 18, fontWeight: '900' },
  deviceShareStatusGold: { color: palette.gold },
  deviceShareStatusBlue: { color: palette.blue },
  deviceShareInfoRow: {
    minHeight: 48,
    justifyContent: 'center',
    gap: 4,
    padding: 11,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  deviceShareInfoLabel: { color: palette.muted, fontSize: 11, fontWeight: '900' },
  deviceShareInfoValue: { color: palette.ink, fontSize: 13, lineHeight: 18, fontWeight: '800' },
  deviceShareAction: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  deviceShareActionIcon: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: palette.greenDark,
  },
  deviceShareActionIconReceive: { backgroundColor: palette.blue },

  clientList: { gap: 10 },
  searchBox: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surfaceSoft,
  },
  searchInput: {
    flex: 1,
    minHeight: 44,
    color: palette.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  filterChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterChip: {
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surface,
  },
  filterChipActive: { borderColor: palette.navy, backgroundColor: palette.navy },
  filterChipText: { color: palette.text, fontSize: 12, fontWeight: '900' },
  filterChipTextActive: { color: '#ffffff' },
  listToolbar: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  listToolbarTitle: { color: palette.ink, fontSize: 14, fontWeight: '900' },
  listToolbarMeta: { color: palette.muted, fontSize: 12, fontWeight: '700' },
  listCountBadge: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: palette.goldSoft,
    color: '#7a5309',
    fontSize: 11,
    fontWeight: '900',
  },
  clientFormActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cancelEditButton: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f3b5ae',
    backgroundColor: palette.redSoft,
  },
  cancelEditButtonText: { color: palette.red, fontSize: 12, fontWeight: '900' },
  clientCard: {
    gap: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  clientCardEditing: { borderColor: palette.blue, backgroundColor: '#eef7ff' },
  clientCollapsedRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  clientCollapsedName: { flex: 1, color: palette.ink, fontSize: 15, fontWeight: '900' },
  clientExpandedDetails: {
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: palette.lineSoft,
  },
  clientUtilityRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  clientUtilityButton: {
    minHeight: 38,
    flexGrow: 1,
    flexBasis: '30%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.surface,
  },
  clientUtilityButtonText: { color: palette.navy2, fontSize: 12, fontWeight: '900' },
  clientInvoiceList: {
    gap: 8,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surface,
  },
  clientInvoiceRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: palette.lineSoft,
  },
  clientSummary: { flex: 1, gap: 3, minWidth: 0 },
  clientName: { color: palette.ink, fontSize: 15, fontWeight: '900' },
  clientMeta: { color: palette.text, fontSize: 13, lineHeight: 18, fontWeight: '600' },
  clientAudit: { color: palette.muted, fontSize: 11, fontWeight: '800', marginTop: 3 },
  clientActionRow: { flexDirection: 'row', gap: 8 },
  editClientButton: {
    minHeight: 40,
    flex: 0.65,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.surface,
  },
  editClientButtonText: { color: palette.navy2, fontSize: 13, fontWeight: '900' },
  useClientButton: {
    minHeight: 40,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 8,
    backgroundColor: palette.navy,
  },
  useClientButtonText: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  savedClientRow: {
    minHeight: 78,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  paginationBar: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingTop: 2,
  },
  paginationButton: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.surface,
  },
  paginationButtonText: { color: palette.navy2, fontSize: 13, fontWeight: '900' },
  paginationText: { color: palette.text, fontSize: 13, fontWeight: '900' },

  accountBadge: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.blueSoft,
  },
  accountName: { color: palette.ink, fontSize: 18, fontWeight: '900' },
  accountRole: { color: palette.navy2, fontSize: 12, fontWeight: '900' },
  accountLine: { color: palette.text, fontSize: 14, fontWeight: '700' },
  accountUserHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  currentUserBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: palette.navy,
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
  },

  editingNotice: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.blueSoft,
  },
  editingNoticeText: { color: palette.navy2, fontSize: 13, fontWeight: '900' },
  invoiceList: { gap: 12 },
  savedInvoiceCard: {
    gap: 11,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  invoiceCollapsedRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  invoiceExpandedDetails: {
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: palette.lineSoft,
  },
  savedInvoiceHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  savedInvoiceNo: { color: palette.ink, fontSize: 17, fontWeight: '900' },
  savedInvoiceMeta: { color: palette.muted, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  savedInvoiceTotalBadge: {
    alignItems: 'flex-end',
    gap: 3,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b8ddcf',
    backgroundColor: palette.greenSoft,
  },
  savedInvoiceStatus: { color: palette.greenDark, fontSize: 10, fontWeight: '900' },
  savedInvoiceTotal: { color: palette.greenDark, fontSize: 13, fontWeight: '900' },
  invoiceActionRow: { flexDirection: 'row', gap: 8 },
  invoicePreviewButton: {
    minHeight: 40,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.surface,
  },
  invoicePreviewButtonText: { color: palette.navy2, fontSize: 13, fontWeight: '900' },
  deleteInvoiceButton: {
    minHeight: 40,
    flex: 0.8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f3b5ae',
    backgroundColor: palette.redSoft,
  },
  deleteInvoiceButtonText: { color: palette.red, fontSize: 13, fontWeight: '900' },
  savedInvoicePreview: {
    gap: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2c46c',
    backgroundColor: palette.surface,
  },

  productCard: {
    gap: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.surfaceSoft,
  },
  productHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  productTitle: { color: palette.text, fontSize: 14, fontWeight: '900' },
  removeButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f3b5ae',
    backgroundColor: palette.redSoft,
  },
  removeButtonDisabled: { opacity: 0.45 },
  chipRow: { gap: 8, paddingRight: 6 },
  productChip: {
    maxWidth: 230,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surface,
  },
  productChipActive: { borderColor: palette.green, backgroundColor: palette.greenSoft },
  productChipDisabled: { opacity: 0.35 },
  productChipText: { color: palette.text, fontSize: 12, fontWeight: '800' },
  productChipTextActive: { color: palette.greenDark },
  rowFields: { gap: 10 },
  switchRow: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  switchText: { color: palette.text, fontSize: 15, fontWeight: '900' },

  finalBillScroll: { paddingBottom: 4 },
  finalBillPage: { width: 690, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#d5d5d5' },
  finalBillHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' },
  finalBillLogo: { width: 86, height: 86, marginLeft: 28 },
  finalBillCompany: { marginTop: 4, color: '#000000', fontSize: 16, fontWeight: '900' },
  finalBillMeta: { alignItems: 'flex-end', paddingBottom: 9 },
  finalBillMetaText: { color: '#000000', fontSize: 21, fontWeight: '500', lineHeight: 27 },
  finalBillMetaLabel: { fontWeight: '900' },
  finalBillGoldLine: { height: 2, marginTop: 8, backgroundColor: '#d0a51f' },
  finalBillParties: { flexDirection: 'row', justifyContent: 'space-between', gap: 28, marginTop: 34 },
  finalBillParty: { flex: 1 },
  finalBillPartyTitle: { marginBottom: 5, color: '#000000', fontSize: 16, fontWeight: '500' },
  finalBillPartyStrong: { color: '#000000', fontSize: 11, fontWeight: '900' },
  finalBillText: { color: '#000000', fontSize: 11, lineHeight: 16 },
  finalBillBlue: { color: '#006fc9', textDecorationLine: 'underline' },
  finalBillBold: { fontWeight: '900', color: '#000000' },
  finalBillTable: { marginTop: 18, borderTopWidth: 1, borderLeftWidth: 1, borderColor: '#c9c9c9' },
  finalBillTableRow: { flexDirection: 'row', minHeight: 31 },
  finalBillTableHead: { backgroundColor: '#f3f3f3' },
  finalBillCell: { paddingHorizontal: 7, paddingVertical: 8, borderRightWidth: 1, borderBottomWidth: 1, borderColor: '#c9c9c9', color: '#000000', fontSize: 10, fontWeight: '500' },
  finalBillColNo: { width: 28 },
  finalBillColProduct: { width: 108 },
  finalBillColHsn: { width: 102 },
  finalBillColQty: { width: 82 },
  finalBillColRate: { width: 62 },
  finalBillColTax: { width: 122 },
  finalBillColAmount: { width: 140 },
  finalBillRight: { textAlign: 'right' },
  finalBillSummary: { borderLeftWidth: 1, borderRightWidth: 1, borderColor: '#c9c9c9' },
  finalBillSummaryLine: { minHeight: 30, flexDirection: 'row', justifyContent: 'flex-end', borderBottomWidth: 1, borderColor: '#c9c9c9' },
  finalBillSummaryLabel: { flex: 1, paddingHorizontal: 8, paddingVertical: 8, color: '#000000', fontSize: 11, fontWeight: '900', textAlign: 'right' },
  finalBillSummaryValue: { width: 124, paddingHorizontal: 8, paddingVertical: 8, borderLeftWidth: 1, borderColor: '#c9c9c9', color: '#000000', fontSize: 11, fontWeight: '500', textAlign: 'right' },
  finalBillGrandLine: { backgroundColor: '#d0aa21' },
  finalBillGrandText: { fontWeight: '900' },
  finalBillWords: { minHeight: 34, padding: 9, borderLeftWidth: 1, borderRightWidth: 1, borderBottomWidth: 1, borderStyle: 'dashed', borderColor: '#c9c9c9', color: '#000000', fontSize: 11, fontWeight: '900', textAlign: 'center' },
  finalBillEway: { paddingVertical: 7, borderLeftWidth: 1, borderRightWidth: 1, borderBottomWidth: 1, borderColor: '#c9c9c9' },
  finalBillEwayRow: { flexDirection: 'row', minHeight: 27 },
  finalBillEwayCell: { width: '50%', paddingHorizontal: 8, color: '#000000', fontSize: 11, lineHeight: 18 },
  finalBillFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 22 },
  finalBillBank: { width: '50%', paddingLeft: 7 },
  finalBillBankTitle: { marginBottom: 18, color: '#000000', fontSize: 11, fontWeight: '900' },
  finalBillSign: { width: 170, alignItems: 'center' },
  finalBillSignature: { width: 150, height: 100, marginTop: 6, marginBottom: 4 },
  actionGrid: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' },
  saveInvoiceButton: {
    flex: 1,
    minWidth: 112,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 8,
    backgroundColor: palette.navy,
    ...cardShadow,
  },
  printButton: {
    flex: 1,
    minWidth: 96,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 8,
    backgroundColor: palette.greenDark,
    ...cardShadow,
  },
  printButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '900' },
  shareButton: {
    flex: 1,
    minWidth: 112,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#b7cde2',
    backgroundColor: palette.surface,
  },
  shareButtonText: { color: palette.navy2, fontSize: 15, fontWeight: '900' },
});
